name: gandy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - deepchem=2.4.0
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.3.3
  - python=3.6.*
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - tensorflow=2.0.0
  - tensorflow_core
  - optuna=2.5.0
